---
- hosts: all
  tasks:
    - name: Verify we are in container
      command: ls -la /.dockerenv

    - name: Detect python used
      command: which python

    - name: List rpm
      shell: rpm -qa | sort

    - name: List pip
      shell: pip freeze | sort
