---
- hosts: all
  tasks:
    - name: Detect python used
      debug:
        msg: '{{ ansible_python_interpreter }}'

    - name: List rpm
      shell: rpm -qa | sort

    - name: List pip
      shell: pip freeze | sort
