---
- hosts: all
  gather_facts: true
  tasks:
    - name: Detect python used
      debug:
        msg: '{{ ansible_facts }}'

    - name: List rpm
      shell: rpm -qa | sort

    - name: List pip
      shell: pip freeze | sort
