---
- hosts: releasevm
  become: true
  tasks:
    - ping:
    - command: id

    - debug:
        msg: '{{ git_private_key }}'

    - command: 'ls -l {{ git_private_key }}'
      ignore_errors: true
      delegate_to: localhost
