---
- hosts: releasevm
  tasks:
    - ping:
    - command: id
    - debug:
        msg: '{{ git_private_key }}'
      ignore_errors: true
    - debug:
        msg: '{{ my_key }}'
      ignore_errors: true
    - command: 'cat {{ my_key }}'
      ignore_errors: true
    - command: 'cat {{ git_private_key }}'
      ignore_errors: true
