---
- hosts: releasevm
  become: true
  tasks:
    - ping:
    - command: id
    - debug:
        msg: '{{ git_private_key }}'
    - command: 'ls -lR /tmp'
      ignore_errors: true
    - command: 'ls -l {{ git_private_key }}'
      ignore_errors: true
