---
- hosts: 2001:19f0:6801:1ea9:5400:01ff:fed7:b84d
  tasks:
    - name: echo lala
      command: echo "lala"

    - setup:
      register: lala

    - debug:
        msg: '{{ ansible_all_ipv6_addresses }}'
