---
- hosts: all
  tasks:
    - name: Display env
      command: env

    - name: Display Red Hat release
      command: cat /etc/redhat-release

    - name: Install vim
      become: True
      package:
        name: vim-minimal
