---
- hosts: all
  gather_facts: false
  order: reverse_inventory
  tasks:
    - command: date
      register: date

    - debug:
        msg: '{{ date }}'

    - set_stats:
        data:
          test_ok: ok
          test_date: '{{ date.changed }}'
        per_host: yes
